# Generated by Django 5.1.15 on 2026-06-27 17:43

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Alerte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('tresorerie_critique', 'Trésorerie Critique'), ('retard_paiement', 'Retard Paiement Client'), ('marge_basse', 'Marge sous Benchmark'), ('score_baisse', 'Score Crédit en Baisse'), ('stock_critique', 'Stock Critique'), ('anomalie_depense', 'Anomalie de Dépenses')], max_length=50)),
                ('seuil', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('statut', models.CharField(choices=[('active', 'Active'), ('resolue', 'Résolue'), ('ignoree', 'Ignorée')], default='active', max_length=20)),
                ('canal', models.CharField(choices=[('sms', 'SMS'), ('email', 'Email'), ('push', 'Push Notification'), ('dashboard', 'Dashboard uniquement')], default='dashboard', max_length=20)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Alerte intelligente',
                'verbose_name_plural': 'Alertes intelligentes',
            },
        ),
        migrations.CreateModel(
            name='Partenaire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=255)),
                ('type', models.CharField(choices=[('banque', 'Banque'), ('microfinance', 'Microfinance'), ('fintech', 'Fintech')], max_length=20)),
                ('api_config', models.JSONField(blank=True, default=dict)),
                ('commission_pct', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
            ],
            options={
                'verbose_name': 'Partenaire Financier',
                'verbose_name_plural': 'Partenaires Financiers',
            },
        ),
        migrations.CreateModel(
            name='PME',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=255)),
                ('secteur', models.CharField(max_length=100)),
                ('siren', models.CharField(max_length=50, unique=True)),
                ('plan', models.CharField(choices=[('starter', 'Starter (Gratuit)'), ('pilote', 'Pilote (15 000 F/mois)'), ('croissance', 'Croissance (45 000 F/mois)')], default='starter', max_length=20)),
                ('nom_schema', models.CharField(max_length=63, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'PME',
                'verbose_name_plural': 'PMEs',
            },
        ),
        migrations.CreateModel(
            name='RapportPDF',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('certifie', 'Rapport Certifié OHADA'), ('simple', 'Analyse Simple')], default='certifie', max_length=20)),
                ('url_s3', models.URLField(max_length=500)),
                ('signature', models.CharField(max_length=255)),
                ('prix', models.DecimalField(decimal_places=2, default=25000.0, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Rapport PDF certifié',
                'verbose_name_plural': 'Rapports PDF certifiés',
            },
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('montant', models.DecimalField(decimal_places=2, max_digits=15)),
                ('type', models.CharField(choices=[('credit', 'Entrée (Crédit)'), ('debit', 'Sortie (Débit)')], max_length=10)),
                ('categorie', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Transaction financière',
                'verbose_name_plural': 'Transactions financières',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('username', models.CharField(blank=True, max_length=150, null=True, unique=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('role', models.CharField(choices=[('dirigeant', 'Dirigeant PME'), ('comptable', 'Comptable PME'), ('operateur', 'Opérateur PME Analytix')], default='dirigeant', max_length=20)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to.', related_name='pme_user_groups', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='pme_user_permissions', to='auth.permission', verbose_name='user permissions')),
                ('pme', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='users', to='core.pme')),
            ],
            options={
                'verbose_name': 'Utilisateur',
                'verbose_name_plural': 'Utilisateurs',
            },
        ),
    ]
