# Generated by Django 5.1.15 on 2026-06-28 00:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='rapportpdf',
            name='statut',
            field=models.CharField(choices=[('en_attente', 'En attente'), ('en_cours', 'En cours'), ('termine', 'Terminé'), ('erreur', 'Erreur')], default='en_attente', max_length=20),
        ),
        migrations.AlterField(
            model_name='rapportpdf',
            name='signature',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='rapportpdf',
            name='url_s3',
            field=models.URLField(blank=True, max_length=500),
        ),
    ]
