# Generated by Django 5.1.15 on 2026-07-01 01:26

from django.db import migrations, models


def migrate_tenant_schemas(apps, schema_editor):
    from django.db import connection
    with connection.cursor() as cursor:
        cursor.execute("SET search_path TO public")
        cursor.execute("SELECT nom_schema FROM core_pme")
        pmes = cursor.fetchall()
        
        for pme in pmes:
            schema_name = pme[0]
            if schema_name == 'public':
                continue
            cursor.execute(f"SET search_path TO {schema_name}")
            cursor.execute("ALTER TABLE core_alerte ADD COLUMN IF NOT EXISTS description TEXT;")
            cursor.execute("ALTER TABLE core_alerte ADD COLUMN IF NOT EXISTS date_critique DATE;")
            cursor.execute("ALTER TABLE core_alerte ADD COLUMN IF NOT EXISTS montant_jeu NUMERIC(15, 2);")
            cursor.execute("ALTER TABLE core_alerte ADD COLUMN IF NOT EXISTS action_recommandee VARCHAR(255);")
            cursor.execute("ALTER TABLE core_alerte ADD COLUMN IF NOT EXISTS lien_direct VARCHAR(255);")
            
        cursor.execute("SET search_path TO public")


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_rendezvous'),
    ]

    operations = [
        migrations.AddField(
            model_name='alerte',
            name='action_recommandee',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='alerte',
            name='date_critique',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='alerte',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='alerte',
            name='lien_direct',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='alerte',
            name='montant_jeu',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True),
        ),
        migrations.RunPython(migrate_tenant_schemas, migrations.RunPython.noop),
    ]
